### ISSUE TITLE
SyntaxError: invalid character in identifier

### ISSUE THREAD

**Issue by nithwith** [codup/odoo-crane#1]
hello,
When i install your module on my odoo 11, i have an error like thant : 

File "<unknown>", line 1
    ﻿# -*- coding: utf-8 -*-
    ^
SyntaxError: invalid character in identifier

Environnement : Ubuntu 16.04, Python 3.5.2

**Comment by diassynthesis** [comment]
Try with:
# -*- coding: utf-8 -*-

**Comment by wowas18** [comment]
fixed in https://github.com/codup/odoo-crane/commit/6b8f7e313eae9898035c5732527d2c42f8bc3fdd
Please test
